### ISSUE TITLE
3 very fringe max enchants crash the site

### ISSUE THREAD

**Issue by KitsuneNoNatsu** [iamcal/enchant-order#5]
So, in 1.14.1 it's possible to enchant armor with EVERY protection type, when doing "inspect element" I was able to switch the toggles from on to off, this works for Chestplate, Leggings, and Bow (for 1.11)
However, for Helmet and Boots, since there's a LOT of enchantments possibly on them, it can't compute it (it is possible, even with SS added at the end), or it enters into a runtime error of some kind, I'm not a coding expert by any means so what do I know
But, I'd like to know if I can help this algorithm in anyway, I know of ways to get maximum helmet and boots enchants while keeping the costs under 39

So that's issue number 1
Number 2: Can you remove the "mutually exclusive" tag from all Armor, and the Bow, as it's "possible"
And write somewhere "This armor is only possible in 1.14.1, go at your own risk" and "This bow is only possible in 1.11, go at your own risk"

That's all, this is very much a hidden gem of a website, and I've been using it a ton!

**Comment by iamcal** [comment]
For the first issue, that's due to the huge number of combinations required to search through, and the memory required. Allowing a greater number of combinations would require a very different approach (probably a non-exhaustive search of some kind) and would be a complete rewrite. Maybe one day!

For the second issue, that's a good idea!
